app:
  # 应用端口
  port: 14020
# 数据库配置
mongodb:
  # 数据库主机
  host: "localhost"
  # 数据库端口
  port: 27017
# 跨域配置
cors:
  # 允许的域名
  allow_origins: ["http://localhost:5173"]
  # 允许携带凭证
  allow_credentials: true
  # 允许的请求方法
  allow_methods: ["POST", "GET", "OPTIONS", "PUT", "DELETE"]
  # 允许的请求头
  allow_headers: ["Content-Type", "Content-Length", "Accept-Encoding", "X-CSRF-Token", "Authorization", "accept", "origin", "Cache-Control", "X-Requested-With"]
  # 预检请求缓存时间
  max_age: 86400
# 邮箱配置
email:
  # 邮箱主机
  host: "smtp.163.com"
  # 邮箱端口 (SSL端口通常是465或994，TLS通常是587)
  port: 465
  # 邮箱用户名 (QQ邮箱通常为完整邮箱地址，如 12345678@qq.com)
  username: "13452552349@163.com"
  # 邮箱密码 (QQ邮箱使用授权码而非登录密码)
  password: "HFkFDwd6FBJRbTkh"
  # 邮箱发件人 (必须使用"名称 <邮箱地址>"格式，必须与username一致)
  from: "DeepSeek-Go <13452552349@163.com>"
  # 是否启用SSL/TLS (QQ邮箱需要设置为true)
  enable_ssl: true
# AI配置
ai:
  # 深度求索配置
  deepseek:
    api_key: "your_api_key_here"
    # 深度求索API基础URL
    base_url: "https://api.deepseek.com"
    # 深度求索API模型
    model: "deepseek-chat"
  kimi:
    api_key: "your_api_key_here"
    # 深度求索API基础URL
    base_url: "https://api.deepseek.com"