app:
  name: "Deepseek-Go"
  port: 14020
database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "your_password_here"
  name: "deepseek"
  charset: "utf8mb4"
  parseTime: true
  loc: "Asia/Shanghai"
  SetMaxIdleConns: 10
  SetMaxOpenConns: 100
  SetConnMaxLifetime: 60
  SetConnMaxIdleTime: 60
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
deepseek:
  api_key: "your_api_key_here"
  base_url: "https://api.deepseek.com"
  model: "deepseek-chat"
  stream: false
  max_tokens: 1000
  temperature: 0.5
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0